GET https://phonebook-self.vercel.app/api/persons

###
GET http://localhost:3002/api/persons


###
GET http://localhost:3002/api/persons/6708afdf6a672d6024195ed2




###
GET https://phonebook-self.vercel.app/info


###
GET https://phonebook-self.vercel.app/